CREATE TABLE ishikawa (
id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
course BIGINT(10) UNSIGNED NOT NULL,
name  VARCHAR(255) NOT NULL,
description TEXT,
timedue BIGINT(10) UNSIGNED NOT NULL,
timeavailable BIGINT(10) UNSIGNED NOT NULL,
timemodified BIGINT(10) UNSIGNED NOT NULL,
PRIMARY KEY (id),
KEY ishi_cou_ix (course)
);
